name: Test
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                persist-credentials: false

            - name: Install Node
              uses: actions/setup-node@v2
        
            - name: Install dependencies
              uses: borales/actions-yarn@v4
              with:
                cmd: install # will run `yarn install` command
          
            - name: Run test
              run:
                yarn build-and-test run