name: Test
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                persist-credentials: false

            - name: Install Node
              uses: actions/setup-node@v2

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Install dependencies
              run:
                pnpm install --frozen-lockfile
          
            - name: Run test
              run:
                pnpm build-and-test run